//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyTestApplicationDBEntities1 : DbContext
    {
        public MyTestApplicationDBEntities1()
            : base("name=MyTestApplicationDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_country> tbl_country { get; set; }
        public DbSet<tbl_state> tbl_state { get; set; }
        public DbSet<tbl_myShop> tbl_myShop { get; set; }
        public DbSet<tbl_Order> tbl_Order { get; set; }
    }
}
