//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public int ID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> SaleAmount { get; set; }
        public string Terms { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public string CustomerStoreStat { get; set; }
        public string CustomerStoreCity { get; set; }
        public string Employee { get; set; }
    }
}
